### ISSUE TITLE
return ampltitudes, duration_times and waiting_times

### ISSUE THREAD

**Issue by gregordecristoforo** [uit-cosmo/superposed-pulses#11]
It would be extremely useful if PointModel would have one or several methods that return the exact amplitude, duration times and waiting times used in the model, equivalent to the uit_scirpts model.

**Comment by Sosnowsky** [comment]
Isn't this already implemented?
https://github.com/uit-cosmo/superposed-pulses/blob/master/model/point_model.py#L59

I agree it is extremely useful.

**Comment by gregordecristoforo** [comment]
Ok, thanks!
