### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by andreped** [uit-cosmo/superposed-pulses#21]
I noticed that matplotlib was added as a dependency. Note that matplotlib depends on PyQt5, which has a permissive license (AFAIK GPL license). This license means that your software will also be forced to have GPL.

Simple solution is to: 1) remove matplotlib as dependency completely, 2) find matplotlib version that is built using PySide instead of PyQt (should exist somewhere), 3) build matplotlib yourself without PyQt, or 4) swap MIT license with GPL (but this hinders people to use your software freely).

**Comment by gregordecristoforo** [comment]
Thanks for pointing this out. I believe removing matplotlib as a dependency is the best solution as it is only used in `example.py`.
